2025-10-06 16:41:46,081 ERROR lp_tenant_importer_v2.main [main.py:148 cmd_import_generic] - File not found: XLSX file not found: .\core_config.xlsx. Hint: try ./lp_tenant_importer_v2/samples/core_config.xlsx or provide an absolute path.
2025-10-06 16:42:28,578 ERROR lp_tenant_importer_v2.main [main.py:145 cmd_import_generic] - Configuration error: Global defaults.target.alert_rules missing in tenants.yml
2025-10-06 16:43:22,786 DEBUG lp_tenant_importer_v2.importers.alert_rules [alert_rules.py:637 _collect_backend_ips] - tenant siems content: {'backends': [NodeRef(id='01925abf82fe0db0a75c190c4316b8a6', name='lb-backend01', ip='10.160.40.202', ip_private='10.41.39.1'), NodeRef(id='01925abf82fe0db0a75c190c4316b8b7', name='lb-backend02', ip='10.160.40.203', ip_private='10.216.206.1')], 'search_heads': [NodeRef(id='19fc63880b018d978aabe9162b851a9d', name='sh01', ip='10.160.40.200', ip_private='')], 'all_in_one': []}
2025-10-06 16:43:22,788 DEBUG lp_tenant_importer_v2.importers.alert_rules [alert_rules.py:645 _collect_backend_ips] - siems private IPs list: ['10.41.39.1', '10.216.206.1']
2025-10-06 16:43:22,788 INFO lp_tenant_importer_v2.core.director_client [director_client.py:684 fetch_resource] - FETCH[ae20cbb4] POST configapi/2bc98ce16a6d4c4c82e362bc11691488/19fc63880b018d978aabe9162b851a9d/AlertRules/MyAlertRules/fetch pool=2bc98ce16a6d4c4c82e362bc11691488 node=19fc63880b018d978aabe9162b851a9d resource=AlertRules/MyAlertRules/fetch
2025-10-06 16:43:22,789 DEBUG lp_tenant_importer_v2.core.director_client [director_client.py:688 fetch_resource] - FETCH[ae20cbb4] payload={"data": {}}
2025-10-06 16:43:22,791 DEBUG urllib3.connectionpool [connectionpool.py:1049 _new_conn] - Starting new HTTPS connection (1): 10.160.144.185:443
2025-10-06 16:43:43,839 ERROR lp_tenant_importer_v2.core.director_client [director_client.py:147 _req] - HTTP POST https://10.160.144.185/configapi/2bc98ce16a6d4c4c82e362bc11691488/19fc63880b018d978aabe9162b851a9d/AlertRules/MyAlertRules/fetch failed: HTTPSConnectionPool(host='10.160.144.185', port=443): Max retries exceeded with url: /configapi/2bc98ce16a6d4c4c82e362bc11691488/19fc63880b018d978aabe9162b851a9d/AlertRules/MyAlertRules/fetch (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002C7AAE79A90>, 'Connection to 10.160.144.185 timed out. (connect timeout=60)'))
2025-10-06 16:43:43,841 INFO lp_tenant_importer_v2.main [main.py:139 cmd_import_generic] - 
| siem                             | node | result | action | status | monitor_ok | monitor_branch | error                                                                                                                                                            | corr |
| -------------------------------- | ---- | ------ | ------ | ------ | ---------- | -------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---- |
| 19fc63880b018d978aabe9162b851a9d | sh01 | error  | fetch  | Failed | —          | —              | HTTPSConnectionPool(host='10.160.144.185', port=443): Max retries exceeded with url: /configapi/2bc98ce16a6d4c4c82e362bc11691488/19fc63880b018d978aabe9162b851a9 | —    |
2025-10-06 16:43:43,841 ERROR lp_tenant_importer_v2.main [main.py:157 cmd_import_generic] - Validation error: One or more operations failed; see rows above.
